### ISSUE TITLE
Is PHP 5.5 required?

### ISSUE THREAD

**Issue by spwilson806** [Potherca/flysystem-github#9]
Currently PHP 5.5 is required for the package.  I glanced quickly through the code and the only place I noticed 5.5 syntax was in the tests.  Would it be reasonable to require 5.5 for dev, but 5.4 otherwise?

**Comment by Potherca** [comment]
I think the major reason to use 5.5 was so that [class name constants](http://php.net/oop5.basic#language.oop5.basic.class.class) could be used in tests.

I checked [the requirements for FlySystem](https://github.com/thephpleague/flysystem/blob/master/composer.json) and they state `"php": ">=5.4.0"` so it would make sense to just follow that.
